// react-demo/src/layout/index.js
/*
 * @Author: Y
 * @Date: 2022-02-14 17:12:40
 * @Description:
 */
import { useEffect, useState } from 'react'
import { Layout, Menu, Breadcrumb } from 'antd'
import { Outlet, useNavigate, useLocation, Link } from 'react-router-dom'
import routes from '../routes'
import style from './index.module.css'
const { Header, Content, Footer } = Layout
const Layouts = () => {
	const history = useNavigate()
	const location = useLocation()
	const [activeMenu, setActiveMenu] = useState('/')

	const pathSnippets = location.pathname.split('/').filter((i) => i)
	const extraBreadcrumbItems = pathSnippets.map((_, index) => {
		const url = `/${pathSnippets.slice(0, index + 1).join('/')}`
		return (
			<Breadcrumb.Item key={url}>
				<Link to={url}>{_}</Link>
			</Breadcrumb.Item>
		)
	})

	const breadcrumbItems = [
		<Breadcrumb.Item key="/">
			<Link to="/">main</Link>
		</Breadcrumb.Item>
	].concat(extraBreadcrumbItems)

	const menuClick = (params) => {
		const { key } = params
		history(key)
	}

	useEffect(() => {
		location.pathname.length < 2
			? setActiveMenu(location.pathname)
			: setActiveMenu(location.pathname.replace(/\//g, ''))
	}, [location])

	console.log({ activeMenu, location, breadcrumbItems })
	return (
		<Layout className="layout" theme="light">
			<Header theme="light" style={{ background: '#fff' }}>
				<div className="logo" />
				<Menu mode="horizontal" selectedKeys={[activeMenu]} onClick={(props) => menuClick(props)}>
					{routes
						.filter((route) => route.menu === 0)
						.map((route) => (
							<Menu.Item key={route.path}>{route.name}</Menu.Item>
						))}
				</Menu>
			</Header>
			<Content style={{ padding: '0 50px' }}>
				<Breadcrumb>{breadcrumbItems}</Breadcrumb>
				<div className={style.content}>{<Outlet />}</div>
			</Content>
			<Footer style={{ textAlign: 'center' }}>Ant Design 2022 Created by Ant UED</Footer>
		</Layout>
	)
}
export default Layouts

// vite-vue3.2.23/src/components/Layout/index.vue
<!--
 * @Author: Y
 * @Date: 2022-03-17 13:38:50
 * @Description: 
-->
<template>
	<a-layout id="components-layout-demo-top" class="layout">
		<a-layout-header>
			<div class="logo" />
			<a-menu theme="dark" mode="horizontal" :default-selected-keys="['2']" :style="{ lineHeight: '64px' }">
				<a-menu-item key="1"> nav 1 </a-menu-item>
				<a-menu-item key="2"> nav 2 </a-menu-item>
				<a-menu-item key="3"> nav 3 </a-menu-item>
			</a-menu>
		</a-layout-header>
		<a-layout-content style="padding: 0 50px">
			<a-breadcrumb style="margin: 16px 0">
				<a-breadcrumb-item>Home</a-breadcrumb-item>
				<a-breadcrumb-item>List</a-breadcrumb-item>
				<a-breadcrumb-item>App</a-breadcrumb-item>
			</a-breadcrumb>
			<div :style="{ background: '#fff', padding: '24px', minHeight: '280px' }">Content</div>
		</a-layout-content>
		<a-layout-footer style="text-align: center"> Ant Design ©2018 Created by Ant UED </a-layout-footer>
	</a-layout>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue'
import { routes } from '@/router'

export default defineComponent({
	setup() {
		const data = reactive({})
		const menus = routes.map((route) => {})

		return {}
	}
})
</script>

<style lang="scss"></style>
